spring.application.name=bff-agendador


usuario.url=usuario:8080/usuario
agendador-tarefas.url=agendador-tarefas:8081/tarefas
notificacao.url=notificacao:8082/email
server.port=8083

cron.horario=0 0/5 * * * ?

usuario.email=admin@admin.com
usuario.senha=1234

logging.level.com.leonardoricardo.bffagendador.infrastructure.client.UsuarioClient=DEBUG
logging.level.feign=DEBUG
